# Generated by Django 5.2 on 2026-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_social_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated', verbose_name='Updated at'),
        ),
    ]
