"""
URL Configuration for Videos Module

This module defines URL routing for video and lesson API endpoints using Django REST Framework's
DefaultRouter. It provides RESTful URL patterns for comprehensive CRUD operations on video and
lesson resources.

Router Configuration:
    - Uses DefaultRouter to automatically generate standard REST API URL patterns
    - Registers two viewsets: VideoViewSet and LessonViewSet
    - Generates 12 total endpoints (6 per viewset) for complete CRUD operations

Generated URL Patterns:
    Videos:
        GET    /api/videos/           - List all videos (filtered/searched/ordered)
        POST   /api/videos/           - Create new video (instructor only)
        GET    /api/videos/{id}/      - Retrieve specific video details
        PUT    /api/videos/{id}/      - Update entire video (instructor only)
        PATCH  /api/videos/{id}/      - Partial update video (instructor only)
        DELETE /api/videos/{id}/      - Delete video (instructor only)

    Lessons:
        GET    /api/lessons/          - List all lessons (role-based filtered)
        POST   /api/lessons/          - Create new lesson (course instructor only)
        GET    /api/lessons/{id}/     - Retrieve specific lesson details with navigation
        PUT    /api/lessons/{id}/     - Update entire lesson (course instructor only)
        PATCH  /api/lessons/{id}/     - Partial update lesson (course instructor only)
        DELETE /api/lessons/{id}/     - Delete lesson (course instructor only)

Integration:
    - Imported in config/urls.py via: path('api/', include('apps.videos.urls'))
    - Works with VideoViewSet and LessonViewSet from views module
    - Supports all filtering, searching, and ordering configured in viewsets
    - Enforces permissions defined in IsCourseInstructorOrReadOnly and IsInstructorOrReadOnly

Route Names (generated by basename):
    Videos:
        - video-list (list/create)
        - video-detail (retrieve/update/destroy)

    Lessons:
        - lesson-list (list/create)
        - lesson-detail (retrieve/update/destroy)
"""

from rest_framework.routers import DefaultRouter

from .views import LessonViewSet, VideoViewSet

# Initialize router for automatic URL pattern generation
router = DefaultRouter()

# Register viewsets with router
# basename parameter defines route name prefixes (e.g., 'video-list', 'video-detail')
router.register("videos", VideoViewSet, basename="video")
router.register("lessons", LessonViewSet, basename="lesson")

# Export URL patterns generated by router
urlpatterns = router.urls
