# Generated by Django 5.2 on 2025-11-05 00:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the student completed this lesson",
                        verbose_name="completed",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the lesson was marked as completed",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "watched_duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total minutes watched (for resume functionality)",
                        verbose_name="watched duration (minutes)",
                    ),
                ),
                (
                    "last_watched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this lesson was watched",
                        null=True,
                        verbose_name="last watched at",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson progress",
                "verbose_name_plural": "lesson progress",
                "ordering": ["enrollment", "lesson__order"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the enrollment occurred",
                        verbose_name="enrolled at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this enrollment is currently active",
                        verbose_name="active",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the student completed the course",
                        verbose_name="completed",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the course was completed",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False,
                        help_text="Whether completion certificate was generated",
                        verbose_name="certificate issued",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Course rating from 1 to 5 stars",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "review",
                    models.TextField(
                        blank=True,
                        help_text="Written review/feedback from student",
                        verbose_name="review",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course the student is enrolled in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "enrollment",
                "verbose_name_plural": "enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
    ]
