# Generated by Django 5.2 on 2026-04-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                help_text="Payment record for this enrollment (null for free courses)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollment",
                to="payments.payment",
                verbose_name="payment",
            ),
        ),
    ]
