# Generated by Django 5.2 on 2025-11-05 00:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Video title", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Video file (MP4, WebM, AVI, etc)",
                        upload_to="videos/%Y/%m/",
                        verbose_name="video file",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Video duration (auto-extracted from file)",
                        null=True,
                        verbose_name="duration",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Video preview thumbnail (auto-generated or custom)",
                        null=True,
                        upload_to="videos/thumbnails/%Y/%m/",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="File size in bytes",
                        verbose_name="file size",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether video has been processed and encoded",
                        verbose_name="processed",
                    ),
                ),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Lesson title", max_length=200, verbose_name="title"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Lesson order within the course (starts at 1)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="order",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed lesson description (what will be covered)",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_free_preview",
                    models.BooleanField(
                        default=False,
                        help_text="Allow non-enrolled users to watch this lesson",
                        verbose_name="free preview",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated lesson duration in minutes",
                        verbose_name="duration (minutes)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this lesson belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "video",
                    models.OneToOneField(
                        help_text="Video file for this lesson",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson",
                        to="videos.video",
                        verbose_name="video",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
                "ordering": ["course", "order"],
                "indexes": [
                    models.Index(
                        fields=["course", "order"],
                        name="videos_less_course__4fe199_idx",
                    ),
                    models.Index(
                        fields=["is_free_preview"],
                        name="videos_less_is_free_61c05b_idx",
                    ),
                ],
                "unique_together": {("course", "order")},
            },
        ),
    ]
