# Generated by Django 5.2 on 2026-03-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Video file (MP4, WebM, AVI, etc)",
                null=True,
                upload_to="videos/%Y/%m/",
                verbose_name="video file",
            ),
        ),
    ]
