# Generated by Django 5.2 on 2026-04-01 22:47

import apps.videos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Video file (MP4, WebM, MOV only - max 2GB)",
                null=True,
                upload_to="videos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "mov"],
                        code="invalid_extension",
                        message="Invalid file extensionAllowed extensions: mp4, webm, mov.",
                    ),
                    apps.videos.validators.validate_video_size,
                    apps.videos.validators.validate_video_mimetype,
                ],
                verbose_name="video file",
            ),
        ),
    ]
