# Generated by Django 5.2 on 2026-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_add_module"),
        ("videos", "0003_add_file_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional module grouping this lesson (must belong to the same course)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="courses.module",
                verbose_name="module",
            ),
        ),
    ]
