# Generated by Django 5.2 on 2026-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_add_lesson_module'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_processed'], name='videos_vide_is_proc_0cc701_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['file_size'], name='videos_vide_file_si_b449c9_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='videos_vide_created_f7522a_idx'),
        ),
    ]
