# Generated by Django 5.2 on 2026-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_videos_vide_is_proc_0cc701_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated', verbose_name='Updated at'),
        ),
    ]
