# Generated by Django 5.2 on 2026-07-07 16:20

import apps.videos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_lesson_updated_at_alter_video_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, help_text='Video file (MP4, WebM, MOV only - max 2GB)', null=True, upload_to='videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'], code='invalid_extension', message='Invalid file extension. Allowed extensions: %(allowed_extensions)s.'), apps.videos.validators.validate_video_size, apps.videos.validators.validate_video_mimetype], verbose_name='video file'),
        ),
    ]
