# Generated by Django 5.2 on 2026-03-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollments", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "certificate_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique validation code (format: WSS-YYYY-XXXXXX)",
                        max_length=15,
                        unique=True,
                        verbose_name="certificate code",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when certificate was issued",
                        verbose_name="issued at",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF file of the certificate",
                        null=True,
                        upload_to="certificates/%Y/%m/",
                        verbose_name="PDF file",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this certificate is valid (allows revocation)",
                        verbose_name="is valid",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        help_text="Enrollment this certificate belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="enrollments.enrollment",
                        verbose_name="enrollment",
                    ),
                ),
            ],
            options={
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["certificate_code"],
                        name="certificate_certifi_0d7e7f_idx",
                    ),
                    models.Index(
                        fields=["enrollment"], name="certificate_enrollm_17cf67_idx"
                    ),
                    models.Index(
                        fields=["-issued_at"], name="certificate_issued__fd4b97_idx"
                    ),
                ],
            },
        ),
    ]
