# Generated by Django 5.2 on 2026-03-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_generation_failed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last PDF generation failure",
                null=True,
                verbose_name="PDF generation failed at",
            ),
        ),
    ]
