# Generated by Django 5.2 on 2026-06-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_certificate_pdf_generation_failed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_code",
            field=models.CharField(
                db_index=True,
                help_text="Unique validation code (format: WSS-YYYY-XXXXXXXXXXXX)",
                max_length=24,
                unique=True,
                verbose_name="certificate code",
            ),
        ),
    ]
