# Generated by Django 5.2 on 2026-06-18 20:35

from django.db import migrations, models


def _full_name(user):
    """Replicate User.get_full_name() (name, else username) or email.

    Historical migration models cannot call model methods, so this mirrors
    ``User.get_full_name() or email`` (see apps/users/models.py and the
    certificates signal). Keep in sync if get_full_name() ever changes.
    """
    name = f"{user.first_name} {user.last_name}".strip()
    return name or user.username or user.email


def backfill_snapshot(apps, schema_editor):
    """Populate the snapshot of already-issued certificates from live data.

    Makes existing certificates immutable too: their snapshot is captured
    once here from the current source values. Idempotent — only fills rows
    whose snapshot is still empty.
    """
    Certificate = apps.get_model("certificates", "Certificate")
    certificates = Certificate.objects.select_related(
        "enrollment__user", "enrollment__course__instructor"
    )
    for cert in certificates.iterator():
        if cert.student_name_snapshot:
            continue
        enrollment = cert.enrollment
        if enrollment is None:
            continue
        instructor = enrollment.course.instructor
        cert.student_name_snapshot = _full_name(enrollment.user)
        cert.course_title_snapshot = enrollment.course.title
        cert.instructor_name_snapshot = _full_name(instructor) if instructor else ""
        cert.completion_date_snapshot = enrollment.completed_at
        cert.save(
            update_fields=[
                "student_name_snapshot",
                "course_title_snapshot",
                "instructor_name_snapshot",
                "completion_date_snapshot",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_alter_certificate_certificate_code"),
        # The backfill traverses enrollment → user / course → instructor, so the
        # historical state must include those fields.
        ("courses", "0003_add_module"),
        ("enrollments", "0003_enrollment_payment"),
        ("users", "0002_add_social_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="completion_date_snapshot",
            field=models.DateTimeField(
                blank=True,
                help_text="Completion date captured when the certificate was issued",
                null=True,
                verbose_name="completion date (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="course_title_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Course title captured when the certificate was issued",
                max_length=200,
                verbose_name="course title (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="instructor_name_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Instructor name captured when the certificate was issued",
                max_length=255,
                verbose_name="instructor name (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="student_name_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Student full name captured when the certificate was issued",
                max_length=255,
                verbose_name="student name (snapshot)",
            ),
        ),
        migrations.RunPython(backfill_snapshot, migrations.RunPython.noop),
    ]
