# Generated by Django 5.2 on 2026-06-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_backfill_certificate_is_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique validation code (format: WSS-YYYY-XXXXXXXXXXXX)",
                max_length=24,
                null=True,
                unique=True,
                verbose_name="certificate code",
            ),
        ),
    ]
