# Generated by Django 5.2 on 2026-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_alter_certificate_certificate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this object was last updated', verbose_name='Updated at'),
        ),
    ]
