# Generated by Django 5.2 on 2026-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_alter_certificate_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='certificate',
            name='certificate_certifi_0d7e7f_idx',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code',
            field=models.CharField(blank=True, help_text='Unique validation code (format: WSS-YYYY-XXXXXXXXXXXX)', max_length=24, null=True, unique=True, verbose_name='certificate code'),
        ),
    ]
