# Generated by Django 5.2 on 2026-07-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_remove_certificate_certificate_certifi_0d7e7f_idx_and_more'),
        ('enrollments', '0004_alter_enrollment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(help_text='Enrollment this certificate belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='enrollments.enrollment', verbose_name='enrollment'),
        ),
    ]
