# Generated by Django 5.2 on 2025-11-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                help_text="User who created this course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="instructor",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["slug"], name="courses_cou_slug_2e551f_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="courses_cou_is_publ_fd1efe_idx",
            ),
        ),
    ]
