# Generated by Django 5.2 on 2026-05-14 16:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this object was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this object last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Module title (e.g., 'Fundamentals')",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the module content",
                        verbose_name="description",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Module position within the course (starts at 1)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="order",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this module belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "module",
                "verbose_name_plural": "modules",
                "ordering": ["course", "order"],
                "indexes": [
                    models.Index(
                        fields=["course", "order"],
                        name="courses_mod_course__20183c_idx",
                    )
                ],
                "unique_together": {("course", "order")},
            },
        ),
    ]
